# Generated by Django 3.0.5 on 2020-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetsInfoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ContactNo', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('University', models.CharField(max_length=100)),
                ('HighestDegree', models.CharField(max_length=50)),
                ('Image', models.ImageField(default='default.jpj', upload_to='user')),
            ],
        ),
        migrations.DeleteModel(
            name='Vets',
        ),
    ]
