# Generated by Django 3.0.5 on 2020-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetsApp', '0002_auto_20200415_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetsinfotable',
            name='Image',
            field=models.ImageField(default='default.jpj', upload_to='vets_images'),
        ),
    ]
