# Generated by Django 3.0.5 on 2020-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='SOME STRING', max_length=20)),
                ('Type', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Color', models.CharField(max_length=30)),
                ('Image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='SOME STRING', max_length=20)),
                ('Type', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Color', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Image', models.CharField(max_length=1000)),
            ],
        ),
    ]
