# Generated by Django 3.0.5 on 2020-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdoptTable',
            new_name='AdoptOfferTable',
        ),
        migrations.RenameModel(
            old_name='BuyTable',
            new_name='BuyOfferTable',
        ),
    ]
