# Generated by Django 3.0.5 on 2020-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_auto_20200415_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptoffertable',
            name='Image',
            field=models.ImageField(default='default.jpj', upload_to='user'),
        ),
        migrations.AlterField(
            model_name='buyoffertable',
            name='Image',
            field=models.ImageField(default='default.jpj', upload_to='user'),
        ),
    ]
