# Generated by Django 3.0.5 on 2020-04-15 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserApp', '0002_auto_20200415_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserInfoTable',
        ),
    ]
