# Generated by Django 3.0.5 on 2020-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0002_auto_20200502_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
