# Generated by Django 3.0.5 on 2020-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0003_auto_20200503_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Name',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
